version: '3'
services:
  dj_mysql:
    container_name: dj-mysql
    image: mysql/mysql-server:8.0.27
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment: 
      MYSQL_DATABASE: dj_treecher
      MYSQL_ROOT_PASSWORD: myP@assw0rd
      MYSQL_ROOT_HOST: '%'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - /opt/docker-volumes/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - dj

  dj_treecher_web:
    container_name: djtreecher-web
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --log-level=debug
    volumes:
      - /opt/docker-volumes/dj-static:/code/static
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - dj_mysql
    networks:
      - dj


networks:
  dj: